### ISSUE TITLE
Getting "module not found 'typescript' when running with DEBUG=*

### ISSUE THREAD

**Issue by Aghassi** [oclif/config#73]
```
  @oclif/config Cannot find typescript { Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/daghassi/git/cli/node_modules/@oclif/config/lib/ts-node.js:9:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3) code: 'MODULE_NOT_FOUND' } +0ms
```

I assume this is an easy fix as right now `typescript` is a dev dependency in this repo, and it needs to be a `dependency` since this relies on it directly.

**Comment by softmarshmallow** [comment]
can you share us your solution?

**Comment by RasPhilCo** [comment]
This was fixed in oclif/config. Are you updated and still experiencing it?
