### ISSUE TITLE
Getting "Cannot find module 'ts-node' when running with DEBUG=*

### ISSUE THREAD

**Issue by arodik** [oclif/config#89]
ts-node is in devDependencies of `@oclif/config` however if I run CLI with DEBUG=* I see the following:
```
@oclif/config Error: Cannot find module 'ts-node'
  @oclif/config Require stack:
  @oclif/config - /Users/arodik/projects/ffbt/node_modules/@oclif/config/lib/ts-node.js
  @oclif/config - /Users/arodik/projects/ffbt/node_modules/@oclif/config/lib/plugin.js
  @oclif/config - /Users/arodik/projects/ffbt/node_modules/@oclif/config/lib/config.js
  @oclif/config - /Users/arodik/projects/ffbt/node_modules/@oclif/config/lib/index.js
  @oclif/config - /Users/arodik/projects/ffbt/node_modules/@oclif/command/lib/command.js
  @oclif/config - /Users/arodik/projects/ffbt/node_modules/@oclif/command/lib/index.js
  @oclif/config - /Users/arodik/projects/ffbt/dist/cli/entrypoint.js
  @oclif/config     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
  @oclif/config     at Function.resolve (internal/modules/cjs/helpers.js:80:19)
  @oclif/config     at registerTSNode (/Users/arodik/projects/ffbt/node_modules/@oclif/config/lib/ts-node.js:19:32)
  @oclif/config     at Object.tsPath (/Users/arodik/projects/ffbt/node_modules/@oclif/config/lib/ts-node.js:77:9)
  @oclif/config     at Plugin.get commandsDir [as commandsDir] (/Users/arodik/projects/ffbt/node_modules/@oclif/config/lib/plugin.js:68:42)
  @oclif/config     at Plugin.get commandIDs [as commandIDs] (/Users/arodik/projects/ffbt/node_modules/@oclif/config/lib/plugin.js:70:19)
  @oclif/config     at Plugin._manifest (/Users/arodik/projects/ffbt/node_modules/@oclif/config/lib/plugin.js:161:28)
  @oclif/config     at async Plugin.load (/Users/arodik/projects/ffbt/node_modules/@oclif/config/lib/plugin.js:56:25)
  @oclif/config     at async Config.load (/Users/arodik/projects/ffbt/node_modules/@oclif/config/lib/config.js:28:9)
  @oclif/config     at async Object.load (/Users/arodik/projects/ffbt/node_modules/@oclif/config/lib/config.js:334:5) +1ms
```

We don't use ts-node because we don't need it
[Our package.json](https://github.com/fluix/ffbt/blob/feature/new-webpack/package.json)

**Comment by RasPhilCo** [comment]
Did you use the oclif generator?

**Comment by arodik** [comment]
No, I didn't
I use Typescript and I notices that the generator works badly with Typescript

**Comment by RasPhilCo** [comment]
I was trying to understand how you created your cli so I can try and reproduce.

**Comment by arodik** [comment]
I had a lot of files in the project when I decided to use OClif, so  I've created the project via `npx oclif multi mynewcli`
Generator settings:
```
? Select a package manager npm
? TypeScript Yes
? Use tslint (linter for TypeScript) No
? Use mocha (testing framework) No
```
Then copied files to my project

**Comment by arodik** [comment]
If you want to reproduce the issue in my package:
`npm i -g ffbt`
`DEBUG=* ffbt`

**Comment by arodik** [comment]
I've found how to reproduce the issue
- Generate new JS project
- add tsconfig.json file

```
 @oclif/config reading core plugin /Users/arodik/projects/mynewcli +0ms
  @oclif/config loadJSON /Users/arodik/projects/mynewcli/package.json +0ms
  @oclif/config loadJSON /Users/arodik/projects/mynewcli/oclif.manifest.json +2ms
  @oclif/config loadJSON /Users/arodik/projects/mynewcli/.oclif.manifest.json +0ms
  @oclif/config registering ts-node at /Users/arodik/projects/mynewcli +0ms
  @oclif/config Error: Cannot find module 'ts-node'
  @oclif/config Require stack:
  @oclif/config - /Users/arodik/projects/mynewcli/node_modules/@oclif/config/lib/ts-node.js
  @oclif/config - /Users/arodik/projects/mynewcli/node_modules/@oclif/config/lib/plugin.js
  @oclif/config - /Users/arodik/projects/mynewcli/node_modules/@oclif/config/lib/config.js
  @oclif/config - /Users/arodik/projects/mynewcli/node_modules/@oclif/config/lib/index.js
  @oclif/config - /Users/arodik/projects/mynewcli/node_modules/@oclif/command/lib/command.js
  @oclif/config - /Users/arodik/projects/mynewcli/node_modules/@oclif/command/lib/index.js
  @oclif/config - /Users/arodik/projects/mynewcli/bin/run
  @oclif/config     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
  @oclif/config     at Function.resolve (internal/modules/cjs/helpers.js:74:19)
  @oclif/config     at registerTSNode (/Users/arodik/projects/mynewcli/node_modules/@oclif/config/lib/ts-node.js:19:32)
  @oclif/config     at Object.tsPath (/Users/arodik/projects/mynewcli/node_modules/@oclif/config/lib/ts-node.js:77:9)
  @oclif/config     at Plugin.get commandsDir [as commandsDir] (/Users/arodik/projects/mynewcli/node_modules/@oclif/config/lib/plugin.js:68:42)
  @oclif/config     at Plugin.get commandIDs [as commandIDs] (/Users/arodik/projects/mynewcli/node_modules/@oclif/config/lib/plugin.js:70:19)
  @oclif/config     at Plugin._manifest (/Users/arodik/projects/mynewcli/node_modules/@oclif/config/lib/plugin.js:161:28)
  @oclif/config     at async Plugin.load (/Users/arodik/projects/mynewcli/node_modules/@oclif/config/lib/plugin.js:56:25)
  @oclif/config     at async Config.load (/Users/arodik/projects/mynewcli/node_modules/@oclif/config/lib/config.js:28:9)
```

**Comment by RasPhilCo** [comment]
Ah, gotcha. We assume if there is a tsconfig.json file in root you are running a typescript project.

**Comment by arodik** [comment]
Yes, I'm running a typescript project, but I don't need ts-node  😀😀

**Comment by arodik** [comment]
I think it's OK to skip `ts-node` if the script can't find it in dependencies :) 
I can try to make PR with fix
